require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - db/**/*
    - .gemspec/**/*
    - .bundle/**/*
    - vendor/**/*
    - config/**/*
    - script/**/*
    - spec/**/*
    - node_modules/**/*
    - tmp/**/*
    - '**/Capfile'

  Include:
    - '**/gems.rb'
    - '**/Rakefile'
    - '**/config.ru'
    - lib/tasks/**/*.rake
    - lib/tasks/**/*.rb

Metrics/ClassLength:
  CountComments: false
  Max: 200
Metrics/LineLength:
  Max: 99
Metrics/MethodLength:
  CountComments: false
  Max: 15
Metrics/AbcSize:
  Max: 25
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

AlignParameters:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Gemspec/OrderedDependencies:
  Enabled: false
Style/Alias:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
